### ISSUE TITLE
Add rate-limit option

### ISSUE THREAD

**Issue by ishani** [ishani/xSyn#2]
.. probably via https://github.com/didip/tollbooth

**Comment by pjv** [comment]
that would be a nice addition.

although it's not part of the API spec, i wish there were a way to impose an auth so that i could create a private service without running inside a VPN.

the canonical API server has a `status.allowNewSyncs` configuration param that would be handy so that you could create a couple sync IDs and then disallow new ones from being created. Does xSyn have anything like that? Could it?

**Comment by ishani** [comment]
Both rate-limiting and your request are available on latest. To do the latter more elegantly, we would probably need the XBS client to allow the user to set a custom header to be sent with every request, like X-Sync-AccessToken or something .. in the Debug or Developer page perhaps. Could then make the servers only accept a certain value.

However, for now:
I added an optional endpoint you can specify - either in the .toml config with `sync_toggle_route` or via the **XS_SEC_SYNCTOGGLE** envvar - that will toggle the ability to add new Sync IDs at runtime. You can also disable new syncs by default using `accept_new_syncs` / **XS_SEC_ACCEPT_NEW_SYNC**.

That way, you can quickly and easily control the sign-up without rebooting the server each time by just visiting that address.

**Comment by pjv** [comment]
wow, that is great work. Thank you!

did you just bang out this go server version of the xbs api for fun?

really nice being able to put up a compact, simple server without all the bloat and dependencies of node and mongodb.

**Comment by ishani** [comment]
That's pretty much my impulse to write it - and any excuse to muck about with Go, really. XBS was exactly what I was after for managing bookmarks and to make it even more perfect, I had to have something lean and self-contained to host with it :)
